services: 
  ctranslate2-build:
    build:
      context: .

    # for debugging
    #entrypoint: tail
    #command: -f /dev/null

    volumes:
      - ./dist:/dist

    # See compatbility matrix: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html
    # you need to compile this for your architecture
    # for GCN 5th gen based GPUs and APUs HSA_OVERRIDE_GFX_VERSION=9.0.0
    # for RDNA 1 based GPUs and APUs HSA_OVERRIDE_GFX_VERSION=10.1.0
    # for RDNA 2 based GPUs and APUs HSA_OVERRIDE_GFX_VERSION=10.3.0
    # for RDNA 3 based GPUs and APUs HSA_OVERRIDE_GFX_VERSION=11.0.0
    environment:
      #- HSA_OVERRIDE_GFX_VERSION=9.0.0
      - PYTORCH_ROCM_ARCH="gfx906"
      - HIP_VISIBLE_DEVICES=0

    devices:
      - /dev/dri:/dev/dri

    security_opt:
      - seccomp:unconfined
    group_add:
      - video
